version: "3.7"
services:

  backend:
    build:
      context: ./backend
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    networks:
      - db_net
    environment:
      - REDDIT_USERNAME=unset
      - REDDIT_PASSWORD=unset
      - REDDIT_CLIENT_ID=unset
      - REDDIT_CLIENT_SECRET=unset
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    depends_on:
      - backend

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=waecm20
    networks:
      - db_net

networks:
  db_net:

