version: "3.7"
services:

  backend:
    build:
      context: ./backend
    ports:
    - target: 8080
      published: 8080
      protocol: tcp

  frontend:
    build:
        context: ./frontend/frontend
    ports:
        - 3000:3000
    volumes:
        - ./frontend:/frontend



