version: "3.7"
services:

  backend:
    build:
      context: ./backend
    ports:
    - target: 8080
      published: 8080
      protocol: tcp

  frontend:
    build:
      context: ./frontend
    ports:
      - target: 3000
        published: 3000
        protocol: tcp

