version: "3.7"
services:

  backend:
    image: macxx/waecm-group-09-backend:abgabe1
    ports:
    - target: 8080
      published: 8080
      protocol: tcp

  frontend:
    image: macxx/waecm-group-09-frontend:abgabe1
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
